
spring.application.name=ipaas-gepics-adapterService
server.address=0.0.0.0
server.port=8086

#rest配置
# 所有以 /api/ 开头的请求都将被 Camel Servlet 处理,默认路径为 /camel/*
camel.servlet.mapping.context-path=/api/*
#建议根据实际场景修改-连接超时:毫秒(默认180000ms)
camel.component.http.connect-timeout=180000
#建议根据实际场景修改-读取超时:毫秒(默认180000ms)
camel.component.http.so-timeout=180000
#建议根据实际场景修改-连接请求超时:从连接池获取连接的超时时间(默认180000ms)
camel.component.http.connection-request-timeout=180000
#rest配置结束

#db配置
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//10.203.24.111:1528/QA058.SGM.COM
spring.datasource.username=SGMSOA_SVCGOV
spring.datasource.password=sgmsoa#2016
#建议根据实际场景修改-最大连接数:连接池中允许的最大连接数,默认10
spring.datasource.hikari.maximum-pool-size=10
#建议根据实际场景修改-最小空闲连接数:连接池中保持的最小空闲连接数,建议小于maximum-pool-size
spring.datasource.hikari.minimum-idle=1
#建议根据实际场景修改-连接超时:等待连接池分配连接的最大时长,单位毫秒,默认30000毫秒
spring.datasource.hikari.connection-timeout=30000
#不建议随意修改-空闲超时时间:连接在连接池中的最大空闲时间,单位毫秒,默认600000毫秒
spring.datasource.hikari.idle-timeout=600000
#不建议随意修改-最大存活时间:连接在连接池中的最大存活时间,单位毫秒,默认1800000毫秒
spring.datasource.hikari.max-lifetime=1800000
#db配置结束

#mq配置
rocketmq.name-server=rocketmq-ns01.apps-qa.saic-gm.com:9876;rocketmq-ns02.apps-qa.saic-gm.com:9876
rocketmq.producer.group=gepics_producer_group
#建议根据实际场景修改-发送超时时间:mq发送消息的超时时间,单位毫秒,默认3000
rocketmq.producer.send-msg-timeout=3000
#不建议随意修改-消息体压缩阈值:消息体超过该阈值则进行压缩,默认4KB
rocketmq.producer.compress-message-body-threshold=4096
#不建议随意修改-最大消息大小:单条消息的最大大小,默认4MB
rocketmq.producer.max-message-size=4194304
#建议根据实际场景修改-同步发送失败重试次数:同步发送失败时的重试次数,默认2次
rocketmq.producer.retry-times-when-send-failed=2
#建议根据实际场景修改-异步发送失败重试次数:异步发送失败时的重试次数,默认2次
rocketmq.producer.retry-times-when-send-async-failed=2
#mq配置结束

#日志配置
#必填-日志保存地址
ipaas.logger.httpPath=http://127.0.0.1:8186/api/saveLog
#选填-日志服务连接超时时间默认1000MS
ipaas.logger.connectTimeout=1000
#选填-日志服务响应超时时间默认1000MS
ipaas.logger.responseTimeout=1000
#选填-日志保存接口线程池线程数配置默认20
ipaas.logger.poolSize=20
#选填-日志保存接口线程池最大线程数配置默认20
ipaas.logger.maxPoolSize=20
#选填-日志保存接口线程池最大队列配置默认2000
ipaas.logger.maxQueueSize=2000
#选填-日志保存接口http客户端最大连接数配置默认200
ipaas.logger.maxTotalConnections=200
#选填-日志保存接口http客户端单个域名连接数配置默认20
ipaas.logger.connectionsPerRoute=20
#日志配置结束